server:
  port: 8895#  ssl:#    key-store: classpath:static/ssl/keystore.p12#    key-alias: localhost#    key-store-password: amar1234#    enabled: true
management:  endpoints:    web:      exposure:        include: "*"
spring:  jpa:    show-sql: true    hibernate:      ddl-auto: create-drop  mail:    host: smtp.gmail.com    username: Amr.java8dev321@gmail.com 
    password:    port: 465    properties:      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true
        transport:
          protocol: smtp
        debug: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 
            client-secret: 
            scope: 
              - https://www.googleapis.com/auth/userinfo.profile
              - https://www.googleapis.com/auth/userinfo.email
          github:
            client-id: 
            client-secret: 
            scope:
              - user:email
              - read:user
              - user:follow
          facebook:
            client-id: 
            client-secret: 
            scope:
              - email
              - public_profile